# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

# diesel.toml
[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
dir = "migrations"
